/**
 * Script para limpiar variables de entorno duplicadas y no utilizadas
 * Genera un reporte de variables a eliminar
 */

const fs = require('fs');
const path = require('path');

// Leer archivo .env.local
const envPath = path.join(__dirname, '.env.local');
const envContent = fs.readFileSync(envPath, 'utf-8');

// Parsear variables del archivo
const envLines = envContent.split('\n');
const envVars = new Map();
const lineNumbers = new Map();

envLines.forEach((line, index) => {
  const trimmed = line.trim();
  // Ignorar comentarios y líneas vacías
  if (!trimmed || trimmed.startsWith('#')) return;

  const match = trimmed.match(/^([A-Z_0-9]+)=/);
  if (match) {
    const varName = match[1];
    if (envVars.has(varName)) {
      // Variable duplicada
      const firstLine = lineNumbers.get(varName);
      console.log(`⚠️  DUPLICADO: ${varName} (líneas ${firstLine + 1} y ${index + 1})`);
    }
    envVars.set(varName, line);
    if (!lineNumbers.has(varName)) {
      lineNumbers.set(varName, index);
    }
  }
});

// Variables usadas en el código (extraídas del grep anterior)
const usedVars = new Set([
  'AES_SIGNATURE_SECRET',
  'AIRTABLE_API_TOKEN',
  'AIRTABLE_BASE_ID',
  'AIRTABLE_PERSONAL_TABLE_ID',
  'AIRTABLE_SISTEMAS_TABLE_ID',
  'AIRTABLE_ROLES_TABLE_ID',
  'AIRTABLE_PF_ID_EMPLEADO',
  'AIRTABLE_PF_FOTO_PERFIL',
  'AIRTABLE_PF_NOMBRE_COMPLETO',
  'AIRTABLE_PF_TIPO_PERSONAL',
  'AIRTABLE_PF_ROL',
  'AIRTABLE_PF_CORREO',
  'AIRTABLE_PF_FECHA_NACIMIENTO',
  'AIRTABLE_PF_FECHA_INCORPORACION',
  'AIRTABLE_PF_TELEFONO',
  'AIRTABLE_PF_NUMERO_DOCUMENTO',
  'AIRTABLE_PF_PASSWORD',
  'AIRTABLE_PF_ACCESOS_ASIGNADOS',
  'AIRTABLE_PF_ESTADO_ACTIVIDAD',
  'AIRTABLE_PF_AREAS',
  'AIRTABLE_PF_ROL_LOOKUP',
  'AIRTABLE_PF_NIVEL_SISTEMA',
  'AIRTABLE_PF_NIVEL_LOOKUP',
  'AIRTABLE_PF_NIVEL_ORDEN_LOOKUP',
  'AIRTABLE_SF_NOMBRE_APP',
  'AIRTABLE_SF_CODIGO_APP',
  'AIRTABLE_RF_NOMBRE_ROL',
  'AIRTABLE_INSUMOS_API_TOKEN',
  'AIRTABLE_INSUMOS_BASE_ID',
  'AIRTABLE_INSUMO_TABLE_ID',
  'AIRTABLE_INS_CODIGO',
  'AIRTABLE_INS_ID',
  'AIRTABLE_INS_NOMBRE',
  'AIRTABLE_INS_UNIDAD_MEDIDA',
  'AIRTABLE_INS_STOCK_MINIMO',
  'AIRTABLE_INS_ESTADO',
  'AIRTABLE_INS_IMAGEN',
  'AIRTABLE_INS_REFERENCIA_COMERCIAL',
  'AIRTABLE_INS_RESPONSABLE',
  'AIRTABLE_INS_CATEGORIA',
  'AIRTABLE_INS_MOVIMIENTOS',
  'AIRTABLE_CAT_INSUMO_TABLE_ID',
  'AIRTABLE_CAT_CODIGO',
  'AIRTABLE_CAT_ID',
  'AIRTABLE_CAT_TIPO',
  'AIRTABLE_CAT_DESCRIPCION',
  'AIRTABLE_CAT_INSUMO',
  'AIRTABLE_MOV_INSUMO_TABLE_ID',
  'AIRTABLE_MOV_CODIGO',
  'AIRTABLE_MOV_ID',
  'AIRTABLE_MOV_CREADA',
  'AIRTABLE_MOV_NOMBRE',
  'AIRTABLE_MOV_CANTIDAD',
  'AIRTABLE_MOV_TIPO',
  'AIRTABLE_MOV_AREA',
  'AIRTABLE_MOV_ID_ORIGEN',
  'AIRTABLE_MOV_RESPONSABLE',
  'AIRTABLE_MOV_INSUMO',
  'AIRTABLE_STOCK_INSUMO_TABLE_ID',
  'AIRTABLE_EPP_CATEGORY_RECORD_ID',
  'AIRTABLE_DOTACION_CATEGORY_RECORD_ID',
  'AIRTABLE_SGSST_API_TOKEN',
  'AIRTABLE_SGSST_BASE_ID',
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_REGION',
  'AWS_S3_BUCKET_NAME',
  'JWT_SECRET',
  'OPENAI_API_KEY',
  'NEXT_PUBLIC_APP_URL',
  'NEXT_PUBLIC_BASE_URL',
  'NEXT_PUBLIC_URL',
  'SENDGRID_API_KEY',
  'SENDGRID_FROM_EMAIL',
  'NODE_ENV'
].concat([
  // Todas las variables AIRTABLE_ que tienen _TABLE_ID o _FIELD
  'AIRTABLE_EVT_TABLE_ID', 'AIRTABLE_ASIS_TABLE_ID', 'AIRTABLE_CAP_TABLE_ID',
  'AIRTABLE_PROG_TABLE_ID', 'AIRTABLE_ENTREGAS_TABLE_ID', 'AIRTABLE_DETALLE_TABLE_ID',
  'AIRTABLE_TOKENS_TABLE_ID', 'AIRTABLE_HIST_TABLE_ID', 'AIRTABLE_INSP_TABLE_ID',
  'AIRTABLE_DETINSP_TABLE_ID', 'AIRTABLE_EQUIP_TABLE_ID', 'AIRTABLE_INSPEQ_TABLE_ID',
  'AIRTABLE_DETEQ_TABLE_ID', 'AIRTABLE_RESPEQ_TABLE_ID', 'AIRTABLE_PRG_BANCO_TABLE_ID',
  'AIRTABLE_PLNT_TABLE_ID', 'AIRTABLE_PXPL_TABLE_ID', 'AIRTABLE_EVALAP_TABLE_ID',
  'AIRTABLE_RESP_TABLE_ID', 'AIRTABLE_MBR_TABLE_ID', 'AIRTABLE_INSPA_TABLE_ID',
  'AIRTABLE_DETINSPA_TABLE_ID', 'AIRTABLE_RESPINSPA_TABLE_ID', 'AIRTABLE_ACCINSPA_TABLE_ID',
  'AIRTABLE_INSPBOT_TABLE_ID', 'AIRTABLE_DETBOT_TABLE_ID', 'AIRTABLE_RESPBOT_TABLE_ID',
  'AIRTABLE_BOTIQUINES_TABLE_ID', 'AIRTABLE_ELEMBOT_TABLE_ID', 'AIRTABLE_INSPEXT_TABLE_ID',
  'AIRTABLE_DETEXT_TABLE_ID', 'AIRTABLE_RESPEXT_TABLE_ID', 'AIRTABLE_EXTINTORES_TABLE_ID',
  'AIRTABLE_INSPCAM_TABLE_ID', 'AIRTABLE_DETCAM_TABLE_ID', 'AIRTABLE_RESPCAM_TABLE_ID',
  'AIRTABLE_CAMILLAS_TABLE_ID', 'AIRTABLE_ELEMCAM_TABLE_ID', 'AIRTABLE_INSPKIT_TABLE_ID',
  'AIRTABLE_DETKIT_TABLE_ID', 'AIRTABLE_VERKIT_TABLE_ID', 'AIRTABLE_RESPKIT_TABLE_ID',
  'AIRTABLE_KITS_TABLE_ID', 'AIRTABLE_ELEMKIT_TABLE_ID', 'AIRTABLE_POLITICAS_TABLE_ID',
  'AIRTABLE_FIRMPOL_TABLE_ID', 'AIRTABLE_TOKPOL_TABLE_ID', 'AIRTABLE_VEH_VEHICULOS_TABLE_ID',
  'AIRTABLE_VEH_DOCUMENTOS_TABLE_ID', 'AIRTABLE_VEH_LICENCIAS_TABLE_ID', 'AIRTABLE_VEH_ALERTAS_TABLE_ID',
  'AIRTABLE_SOCIO_BASE_ID', 'AIRTABLE_SOCIO_CAMPANAS_TABLE_ID', 'AIRTABLE_SOCIO_RESPUESTAS_TABLE_ID',
  'AIRTABLE_SOCIO_TOKENS_TABLE_ID', 'AIRTABLE_SOCIO_INFORMES_TABLE_ID', 'AIRTABLE_IND_REGISTROS_TABLE_ID',
  'AIRTABLE_IND_TOKENS_FIRMA_TABLE_ID', 'AIRTABLE_IND_CONSTANCIAS_TABLE_ID', 'AIRTABLE_IND_ALERTAS_LOG_TABLE_ID',
  'AIRTABLE_NOMINA_TABLE_ID', 'MIEMBROS_COMITE_TABLE_ID', 'ASISTENCIA_COMITES_TABLE_ID',
  'COMPROMISOS_TABLE_ID', 'COPASST_ACTAS_TABLE_ID', 'COPASST_CONDICIONES_TABLE_ID',
  'COCOLAB_ACTAS_TABLE_ID', 'COCOLAB_ACCIONES_TABLE_ID', 'COPASST_ACTAS_ID_FIELD',
  'COPASST_ACTAS_NUMERO_ACTA_FIELD'
]).concat([
  // Todos los field IDs que se encuentran en el código
  'AIRTABLE_EVT_CODIGO', 'AIRTABLE_EVT_CIUDAD', 'AIRTABLE_EVT_LUGAR', 'AIRTABLE_EVT_FECHA',
  'AIRTABLE_EVT_HORA_INICIO', 'AIRTABLE_EVT_DURACION', 'AIRTABLE_EVT_AREA', 'AIRTABLE_EVT_TIPO',
  'AIRTABLE_EVT_TEMAS_TRATADOS', 'AIRTABLE_EVT_NOMBRE_CONFERENCISTA', 'AIRTABLE_EVT_ESTADO',
  'AIRTABLE_EVT_ASISTENCIA_LINK', 'AIRTABLE_EVT_PROGRAMACION_LINK', 'AIRTABLE_EVT_FIRMA_CONFERENCISTA',
  'AIRTABLE_ASIS_ID_ASISTENCIA', 'AIRTABLE_ASIS_NOMBRES', 'AIRTABLE_ASIS_CEDULA', 'AIRTABLE_ASIS_LABOR',
  'AIRTABLE_ASIS_FIRMA_CONFIRMADA', 'AIRTABLE_ASIS_FECHA_REGISTRO', 'AIRTABLE_ASIS_EVENTO_LINK',
  'AIRTABLE_ASIS_ID_EMPLEADO_CORE', 'AIRTABLE_ASIS_PROGRAMACION_LINK', 'AIRTABLE_ASIS_FIRMA',
  'AIRTABLE_CAP_CODIGO', 'AIRTABLE_CAP_NOMBRE', 'AIRTABLE_CAP_INTENSIDAD', 'AIRTABLE_CAP_TIPO',
  'AIRTABLE_CAP_CATEGORIA', 'AIRTABLE_CAP_POBLACION', 'AIRTABLE_PROG_IDENTIFICADOR', 'AIRTABLE_PROG_MES',
  'AIRTABLE_PROG_TRIMESTRE', 'AIRTABLE_PROG_PROGRAMADO', 'AIRTABLE_PROG_EJECUTADO',
  'AIRTABLE_PROG_FECHA_EJECUCION', 'AIRTABLE_PROG_TOTAL_ASISTENTES', 'AIRTABLE_PROG_CAPACITACION_LINK',
  'AIRTABLE_PROG_EVENTOS_LINK', 'AIRTABLE_PROG_OBSERVACIONES', 'AIRTABLE_PROG_ASISTENCIA_LINK',
  'AIRTABLE_ENT_ID_ENTREGA', 'AIRTABLE_ENT_ID', 'AIRTABLE_ENT_FECHA_ENTREGA', 'AIRTABLE_ENT_RESPONSABLE',
  'AIRTABLE_ENT_OBSERVACIONES', 'AIRTABLE_ENT_FECHA_CONFIRMACION', 'AIRTABLE_ENT_DETALLE_LINK',
  'AIRTABLE_ENT_TOKENS_LINK', 'AIRTABLE_ENT_ACTIVIDADES_SST', 'AIRTABLE_ENT_ID_EMPLEADO_CORE',
  'AIRTABLE_ENT_ESTADO', 'AIRTABLE_ENT_MOTIVO', 'AIRTABLE_ENT_HISTORIAL_LINK', 'AIRTABLE_ENT_FOTO_EVIDENCIA_URL',
  'AIRTABLE_DET_ID', 'AIRTABLE_DET_CANTIDAD', 'AIRTABLE_DET_VIDA_UTIL', 'AIRTABLE_DET_FECHA_VENCIMIENTO',
  'AIRTABLE_DET_OBSERVACIONES', 'AIRTABLE_DET_ENTREGA_LINK', 'AIRTABLE_DET_TALLA', 'AIRTABLE_DET_CONDICION',
  'AIRTABLE_DET_CODIGO_INSUMO', 'AIRTABLE_TOK_TOKEN_ID', 'AIRTABLE_TOK_FECHA_GENERACION',
  'AIRTABLE_TOK_FECHA_EXPIRACION', 'AIRTABLE_TOK_TIPO_VERIFICACION', 'AIRTABLE_TOK_HASH_FIRMA',
  'AIRTABLE_TOK_ENTREGA_LINK', 'AIRTABLE_TOK_ID_EMPLEADO_CORE', 'AIRTABLE_TOK_ESTADO',
  'AIRTABLE_HIST_DIAS_RESTANTES', 'AIRTABLE_HIST_FECHA_ENTREGA', 'AIRTABLE_HIST_FECHA_VENCIMIENTO',
  'AIRTABLE_HIST_ESTADO', 'AIRTABLE_HIST_ID_EMPLEADO_CORE', 'AIRTABLE_HIST_REQUIERE_REPOSICION',
  'AIRTABLE_HIST_ENTREGA_ORIGEN', 'AIRTABLE_HIST_CODIGO_INSUMO', 'AIRTABLE_INSP_ID', 'AIRTABLE_INSP_FECHA',
  'AIRTABLE_INSP_INSPECTOR', 'AIRTABLE_INSP_ESTADO', 'AIRTABLE_INSP_DETALLE_LINK', 'AIRTABLE_INSP_URL_DOCUMENTO',
  'AIRTABLE_INSP_FECHA_EXPORTACION', 'AIRTABLE_INSP_RESPONSABLE_FIRMANTE', 'AIRTABLE_INSP_COPASST_FIRMANTE',
  'AIRTABLE_DETINSP_ID', 'AIRTABLE_DETINSP_ID_EMPLEADO', 'AIRTABLE_DETINSP_NOMBRE', 'AIRTABLE_DETINSP_OBSERVACIONES',
  'AIRTABLE_DETINSP_FIRMA', 'AIRTABLE_DETINSP_INSPECCION_LINK', 'AIRTABLE_DETINSP_CASCO',
  'AIRTABLE_DETINSP_P_AUDITIVA', 'AIRTABLE_DETINSP_P_VISUAL', 'AIRTABLE_DETINSP_P_RESPIRATORIA',
  'AIRTABLE_DETINSP_ROPA', 'AIRTABLE_DETINSP_GUANTES', 'AIRTABLE_DETINSP_BOTAS', 'AIRTABLE_DETINSP_P_CAIDAS',
  'AIRTABLE_DETINSP_OTROS', 'AIRTABLE_EQUIP_CODIGO', 'AIRTABLE_EQUIP_NOMBRE', 'AIRTABLE_EQUIP_CATEGORIA',
  'AIRTABLE_EQUIP_TIPO_ESPECIFICO', 'AIRTABLE_EQUIP_AREA', 'AIRTABLE_EQUIP_UBICACION', 'AIRTABLE_EQUIP_CAPACIDAD',
  'AIRTABLE_EQUIP_FECHA_VENCIMIENTO', 'AIRTABLE_EQUIP_ESTADO', 'AIRTABLE_EQUIP_DESCRIPCION',
  'AIRTABLE_EQUIP_ID_AREA_CORE', 'AIRTABLE_INSPEQ_ID', 'AIRTABLE_INSPEQ_FECHA', 'AIRTABLE_INSPEQ_INSPECTOR',
  'AIRTABLE_INSPEQ_ESTADO', 'AIRTABLE_INSPEQ_OBSERVACIONES', 'AIRTABLE_INSPEQ_URL_DOCUMENTO',
  'AIRTABLE_INSPEQ_FECHA_EXPORTACION', 'AIRTABLE_DETEQ_ID', 'AIRTABLE_DETEQ_INSPECCION_LINK',
  'AIRTABLE_DETEQ_EQUIPO_LINK', 'AIRTABLE_DETEQ_CATEGORIA', 'AIRTABLE_DETEQ_AREA', 'AIRTABLE_DETEQ_ESTADO_GENERAL',
  'AIRTABLE_DETEQ_SENALIZACION', 'AIRTABLE_DETEQ_ACCESIBILIDAD', 'AIRTABLE_DETEQ_PRESION_MANOMETRO',
  'AIRTABLE_DETEQ_MANGUERA', 'AIRTABLE_DETEQ_PIN_SEGURIDAD', 'AIRTABLE_DETEQ_SOPORTE_BASE',
  'AIRTABLE_DETEQ_COMPLETITUD', 'AIRTABLE_DETEQ_ESTADO_CONTENEDOR', 'AIRTABLE_DETEQ_ESTRUCTURA',
  'AIRTABLE_DETEQ_CORREAS', 'AIRTABLE_DETEQ_FECHA_VENCIMIENTO', 'AIRTABLE_DETEQ_OBSERVACIONES',
  'AIRTABLE_DETEQ_FOTO_URL', 'AIRTABLE_RESPEQ_ID_FIRMA', 'AIRTABLE_RESPEQ_INSPECCION_LINK',
  'AIRTABLE_RESPEQ_TIPO', 'AIRTABLE_RESPEQ_NOMBRE', 'AIRTABLE_RESPEQ_CEDULA', 'AIRTABLE_RESPEQ_CARGO',
  'AIRTABLE_RESPEQ_FIRMA', 'AIRTABLE_RESPEQ_FECHA_FIRMA', 'AIRTABLE_PRG_BANCO_CODIGO',
  'AIRTABLE_PRG_BANCO_TEXTO', 'AIRTABLE_PRG_BANCO_TIPO', 'AIRTABLE_PRG_BANCO_OPCIONES_JSON',
  'AIRTABLE_PRG_BANCO_RESPUESTA_CORRECTA', 'AIRTABLE_PRG_BANCO_CATEGORIA', 'AIRTABLE_PRG_BANCO_DIFICULTAD',
  'AIRTABLE_PRG_BANCO_ESTADO', 'AIRTABLE_PRG_BANCO_PUNTAJE_BASE', 'AIRTABLE_PRG_BANCO_EXPLICACION',
  'AIRTABLE_PLNT_CODIGO', 'AIRTABLE_PLNT_NOMBRE', 'AIRTABLE_PLNT_DESCRIPCION', 'AIRTABLE_PLNT_TIPO',
  'AIRTABLE_PLNT_PUNTAJE_MINIMO', 'AIRTABLE_PLNT_TIEMPO_LIMITE', 'AIRTABLE_PLNT_INTENTOS',
  'AIRTABLE_PLNT_ALEATORIZAR', 'AIRTABLE_PLNT_MOSTRAR_RETRO', 'AIRTABLE_PLNT_ESTADO', 'AIRTABLE_PLNT_VIGENCIA',
  'AIRTABLE_PLNT_PREGUNTAS_LINK', 'AIRTABLE_PLNT_POBLACION', 'AIRTABLE_PLNT_CATEGORIAS',
  'AIRTABLE_PLNT_PROGRAMACIONES', 'AIRTABLE_PXPL_CODIGO', 'AIRTABLE_PXPL_PLANTILLA', 'AIRTABLE_PXPL_PREGUNTA',
  'AIRTABLE_PXPL_ORDEN', 'AIRTABLE_PXPL_PUNTAJE', 'AIRTABLE_PXPL_OBLIGATORIA', 'AIRTABLE_EVALAP_ID',
  'AIRTABLE_EVALAP_PLANTILLA', 'AIRTABLE_EVALAP_PROG_MENSUAL', 'AIRTABLE_EVALAP_FECHA',
  'AIRTABLE_EVALAP_ID_EMPLEADO', 'AIRTABLE_EVALAP_NOMBRES', 'AIRTABLE_EVALAP_CEDULA', 'AIRTABLE_EVALAP_CARGO',
  'AIRTABLE_EVALAP_PUNTAJE_OBT', 'AIRTABLE_EVALAP_PUNTAJE_MAX', 'AIRTABLE_EVALAP_PORCENTAJE',
  'AIRTABLE_EVALAP_ESTADO', 'AIRTABLE_EVALAP_INTENTO', 'AIRTABLE_EVALAP_TIEMPO', 'AIRTABLE_EVALAP_EVALUADOR',
  'AIRTABLE_EVALAP_OBSERVACIONES', 'AIRTABLE_EVALAP_PROG_CAP', 'AIRTABLE_EVALAP_RESP_LINK',
  'AIRTABLE_RESP_ID', 'AIRTABLE_RESP_EVALUACION', 'AIRTABLE_RESP_PREGUNTA', 'AIRTABLE_RESP_RESPUESTA_DADA',
  'AIRTABLE_RESP_ES_CORRECTA', 'AIRTABLE_RESP_PUNTAJE', 'AIRTABLE_RESP_TIEMPO_SEG', 'AIRTABLE_RESP_ORDEN',
  'AIRTABLE_MBR_ID', 'AIRTABLE_MBR_ID_EMPLEADO', 'AIRTABLE_MBR_NOMBRE', 'AIRTABLE_MBR_DOCUMENTO',
  'AIRTABLE_MBR_CARGO', 'AIRTABLE_MBR_COMITE', 'AIRTABLE_MBR_ROL', 'AIRTABLE_MBR_REPRESENTACION',
  'AIRTABLE_MBR_ESTADO', 'AIRTABLE_MBR_EXCLUIR_ASISTENCIA', 'AIRTABLE_INSPA_ID', 'AIRTABLE_INSPA_FECHA',
  'AIRTABLE_INSPA_INSPECTOR', 'AIRTABLE_INSPA_AREA', 'AIRTABLE_INSPA_ESTADO', 'AIRTABLE_INSPA_OBSERVACIONES',
  'AIRTABLE_INSPA_URL_DOCUMENTO', 'AIRTABLE_INSPA_FECHA_EXPORTACION', 'AIRTABLE_INSPA_DETALLE_LINK',
  'AIRTABLE_INSPA_RESPONSABLES_LINK', 'AIRTABLE_INSPA_ACCIONES_LINK', 'AIRTABLE_INSPA_FOTO_URL',
  'AIRTABLE_DETINSPA_ID', 'AIRTABLE_DETINSPA_INSPECCION_LINK', 'AIRTABLE_DETINSPA_CATEGORIA',
  'AIRTABLE_DETINSPA_CRITERIO', 'AIRTABLE_DETINSPA_CONDICION', 'AIRTABLE_DETINSPA_OBSERVACION',
  'AIRTABLE_RESPINSPA_ID_FIRMA', 'AIRTABLE_RESPINSPA_INSPECCION_LINK', 'AIRTABLE_RESPINSPA_TIPO',
  'AIRTABLE_RESPINSPA_NOMBRE', 'AIRTABLE_RESPINSPA_CEDULA', 'AIRTABLE_RESPINSPA_CARGO',
  'AIRTABLE_RESPINSPA_FIRMA', 'AIRTABLE_RESPINSPA_FECHA_FIRMA', 'AIRTABLE_ACCINSPA_ID',
  'AIRTABLE_ACCINSPA_INSPECCION_LINK', 'AIRTABLE_ACCINSPA_DESCRIPCION', 'AIRTABLE_ACCINSPA_TIPO',
  'AIRTABLE_ACCINSPA_RESPONSABLE', 'AIRTABLE_ACCINSPA_FECHA_PROPUESTA', 'AIRTABLE_ACCINSPA_ESTADO',
  'AIRTABLE_ACCINSPA_FECHA_CIERRE', 'AIRTABLE_ACCINSPA_EVIDENCIA_URL', 'AIRTABLE_ACCINSPA_CRITERIO_LINK'
]).concat([
  // Inspecciones específicas
  'AIRTABLE_INSPBOT_ID', 'AIRTABLE_INSPBOT_FECHA', 'AIRTABLE_INSPBOT_INSPECTOR', 'AIRTABLE_INSPBOT_CARGO_INSPECTOR',
  'AIRTABLE_INSPBOT_ESTADO', 'AIRTABLE_INSPBOT_OBSERVACIONES', 'AIRTABLE_INSPBOT_URL_DOCUMENTO',
  'AIRTABLE_INSPBOT_FECHA_EXPORTACION', 'AIRTABLE_INSPBOT_DETALLE_LINK', 'AIRTABLE_INSPBOT_RESPONSABLES_LINK',
  'AIRTABLE_DETBOT_ID', 'AIRTABLE_DETBOT_INSPECCION_LINK', 'AIRTABLE_DETBOT_BOTIQUIN_LINK',
  'AIRTABLE_DETBOT_ELEMENTO_LINK', 'AIRTABLE_DETBOT_ESTADO_ELEMENTO', 'AIRTABLE_DETBOT_CANTIDAD',
  'AIRTABLE_DETBOT_FECHA_VENCIMIENTO', 'AIRTABLE_DETBOT_OBSERVACIONES', 'AIRTABLE_RESPBOT_ID_FIRMA',
  'AIRTABLE_RESPBOT_INSPECCION_LINK', 'AIRTABLE_RESPBOT_TIPO', 'AIRTABLE_RESPBOT_NOMBRE',
  'AIRTABLE_RESPBOT_CARGO', 'AIRTABLE_RESPBOT_FIRMADO', 'AIRTABLE_RESPBOT_FECHA_FIRMA',
  'AIRTABLE_BOTIQUINES_CODIGO', 'AIRTABLE_BOTIQUINES_NOMBRE', 'AIRTABLE_BOTIQUINES_TIPO_LINK',
  'AIRTABLE_BOTIQUINES_UBICACION_LINK', 'AIRTABLE_BOTIQUINES_FECHA_INSTALACION', 'AIRTABLE_BOTIQUINES_ESTADO',
  'AIRTABLE_BOTIQUINES_ID_AREA_CORE', 'AIRTABLE_ELEMBOT_CODIGO', 'AIRTABLE_ELEMBOT_NOMBRE',
  'AIRTABLE_ELEMBOT_UNIDAD', 'AIRTABLE_ELEMBOT_REQUIERE_VENCIMIENTO', 'AIRTABLE_ELEMBOT_DESCRIPCION',
  'AIRTABLE_ELEMBOT_ESTADO', 'AIRTABLE_INSPEXT_ID', 'AIRTABLE_INSPEXT_FECHA', 'AIRTABLE_INSPEXT_INSPECTOR',
  'AIRTABLE_INSPEXT_CARGO_INSPECTOR', 'AIRTABLE_INSPEXT_ESTADO', 'AIRTABLE_INSPEXT_OBSERVACIONES',
  'AIRTABLE_INSPEXT_URL_DOCUMENTO', 'AIRTABLE_INSPEXT_FECHA_EXPORTACION', 'AIRTABLE_INSPEXT_DETALLE_LINK',
  'AIRTABLE_INSPEXT_RESPONSABLES_LINK', 'AIRTABLE_DETEXT_ID', 'AIRTABLE_DETEXT_INSPECCION_LINK',
  'AIRTABLE_DETEXT_EXTINTOR_LINK', 'AIRTABLE_DETEXT_PRESION', 'AIRTABLE_DETEXT_SELLO_GARANTIA',
  'AIRTABLE_DETEXT_MANOMETRO', 'AIRTABLE_DETEXT_ESTADO_CILINDRO', 'AIRTABLE_DETEXT_MANIJA',
  'AIRTABLE_DETEXT_BOQUILLA_MANGUERA', 'AIRTABLE_DETEXT_ANILLO_SEGURIDAD', 'AIRTABLE_DETEXT_PIN_SEGURIDAD',
  'AIRTABLE_DETEXT_PINTURA', 'AIRTABLE_DETEXT_TARJETA_INSPECCION', 'AIRTABLE_DETEXT_OBSERVACIONES',
  'AIRTABLE_DETEXT_INFO_SNAPSHOT_LINK', 'AIRTABLE_RESPEXT_ID_FIRMA', 'AIRTABLE_RESPEXT_INSPECCION_LINK',
  'AIRTABLE_RESPEXT_TIPO', 'AIRTABLE_RESPEXT_NOMBRE', 'AIRTABLE_RESPEXT_CARGO', 'AIRTABLE_RESPEXT_FIRMADO',
  'AIRTABLE_RESPEXT_FECHA_FIRMA', 'AIRTABLE_EXTINTORES_CODIGO', 'AIRTABLE_EXTINTORES_NOMBRE',
  'AIRTABLE_EXTINTORES_ESTADO', 'AIRTABLE_EXTINTORES_UBICACION', 'AIRTABLE_INSPCAM_ID', 'AIRTABLE_INSPCAM_FECHA',
  'AIRTABLE_INSPCAM_INSPECTOR', 'AIRTABLE_INSPCAM_CARGO_INSPECTOR', 'AIRTABLE_INSPCAM_ESTADO',
  'AIRTABLE_INSPCAM_OBSERVACIONES', 'AIRTABLE_INSPCAM_URL_DOCUMENTO', 'AIRTABLE_INSPCAM_FECHA_EXPORTACION',
  'AIRTABLE_INSPCAM_DETALLE_LINK', 'AIRTABLE_INSPCAM_RESPONSABLES_LINK', 'AIRTABLE_DETCAM_ID',
  'AIRTABLE_DETCAM_INSPECCION_LINK', 'AIRTABLE_DETCAM_CAMILLA_LINK', 'AIRTABLE_DETCAM_ELEMENTO_LINK',
  'AIRTABLE_DETCAM_ESTADO_ELEMENTO', 'AIRTABLE_DETCAM_CANTIDAD', 'AIRTABLE_DETCAM_OBSERVACIONES',
  'AIRTABLE_RESPCAM_ID_FIRMA', 'AIRTABLE_RESPCAM_INSPECCION_LINK', 'AIRTABLE_RESPCAM_TIPO',
  'AIRTABLE_RESPCAM_NOMBRE', 'AIRTABLE_RESPCAM_CARGO', 'AIRTABLE_RESPCAM_FIRMADO', 'AIRTABLE_RESPCAM_FECHA_FIRMA',
  'AIRTABLE_CAMILLAS_CODIGO', 'AIRTABLE_CAMILLAS_NOMBRE', 'AIRTABLE_CAMILLAS_UBICACION', 'AIRTABLE_CAMILLAS_ESTADO',
  'AIRTABLE_ELEMCAM_CODIGO', 'AIRTABLE_ELEMCAM_NOMBRE', 'AIRTABLE_ELEMCAM_ESTADO', 'AIRTABLE_INSPKIT_ID',
  'AIRTABLE_INSPKIT_FECHA', 'AIRTABLE_INSPKIT_INSPECTOR', 'AIRTABLE_INSPKIT_CARGO_INSPECTOR',
  'AIRTABLE_INSPKIT_ESTADO', 'AIRTABLE_INSPKIT_OBSERVACIONES', 'AIRTABLE_INSPKIT_URL_DOCUMENTO',
  'AIRTABLE_INSPKIT_FECHA_EXPORTACION', 'AIRTABLE_INSPKIT_DETALLE_LINK', 'AIRTABLE_INSPKIT_VERIFICACIONES_LINK',
  'AIRTABLE_INSPKIT_RESPONSABLES_LINK', 'AIRTABLE_DETKIT_ID', 'AIRTABLE_DETKIT_INSPECCION_LINK',
  'AIRTABLE_DETKIT_KIT_LINK', 'AIRTABLE_DETKIT_ELEMENTO_LINK', 'AIRTABLE_DETKIT_ESTADO_ELEMENTO',
  'AIRTABLE_DETKIT_CANTIDAD', 'AIRTABLE_DETKIT_FECHA_VENCIMIENTO', 'AIRTABLE_DETKIT_OBSERVACIONES',
  'AIRTABLE_VERKIT_ID', 'AIRTABLE_VERKIT_INSPECCION_LINK', 'AIRTABLE_VERKIT_CONOCE_PROCEDIMIENTO',
  'AIRTABLE_VERKIT_ALMACENAMIENTO_ADECUADO', 'AIRTABLE_VERKIT_ROTULADO_SENALIZADO', 'AIRTABLE_RESPKIT_ID_FIRMA',
  'AIRTABLE_RESPKIT_INSPECCION_LINK', 'AIRTABLE_RESPKIT_TIPO', 'AIRTABLE_RESPKIT_NOMBRE',
  'AIRTABLE_RESPKIT_CARGO', 'AIRTABLE_RESPKIT_FIRMADO', 'AIRTABLE_RESPKIT_FECHA_FIRMA',
  'AIRTABLE_KITSDER_CODIGO', 'AIRTABLE_KITSDER_NOMBRE', 'AIRTABLE_KITSDER_UBICACION', 'AIRTABLE_KITSDER_ESTADO',
  'AIRTABLE_ELEMKIT_CODIGO', 'AIRTABLE_ELEMKIT_NOMBRE', 'AIRTABLE_ELEMKIT_ESTADO'
]).concat([
  // Políticas
  'AIRTABLE_POL_ID', 'AIRTABLE_POL_CODIGO', 'AIRTABLE_POL_TITULO', 'AIRTABLE_POL_DESCRIPCION',
  'AIRTABLE_POL_URL_DOCUMENTO', 'AIRTABLE_POL_CATEGORIA', 'AIRTABLE_POL_VERSION', 'AIRTABLE_POL_FECHA_VIGENCIA',
  'AIRTABLE_POL_ESTADO', 'AIRTABLE_POL_FECHA_CREACION', 'AIRTABLE_POL_FECHA_MODIFICACION',
  'AIRTABLE_POL_FECHA_PUBLICACION', 'AIRTABLE_POL_CREADO_POR', 'AIRTABLE_POL_MODIFICADO_POR',
  'AIRTABLE_POL_REQUIERE_FIRMA', 'AIRTABLE_POL_ORDEN', 'AIRTABLE_POL_VISIBLE', 'AIRTABLE_POL_FIRMAS_LINK',
  'AIRTABLE_FIRMPOL_ID', 'AIRTABLE_FIRMPOL_ID_EMPLEADO', 'AIRTABLE_FIRMPOL_NOMBRE_EMPLEADO',
  'AIRTABLE_FIRMPOL_POLITICA_LINK', 'AIRTABLE_FIRMPOL_FECHA_FIRMA', 'AIRTABLE_FIRMPOL_FIRMA',
  'AIRTABLE_FIRMPOL_IP_ADDRESS', 'AIRTABLE_FIRMPOL_USER_AGENT', 'AIRTABLE_TOKPOL_TOKEN_ID',
  'AIRTABLE_TOKPOL_ID_EMPLEADO', 'AIRTABLE_TOKPOL_POLITICA_LINK', 'AIRTABLE_TOKPOL_FECHA_GENERACION',
  'AIRTABLE_TOKPOL_FECHA_EXPIRACION', 'AIRTABLE_TOKPOL_ESTADO'
]).concat([
  // Vehicular
  'AIRTABLE_VEH_VEH_ID', 'AIRTABLE_VEH_VEH_PLACA', 'AIRTABLE_VEH_VEH_TIPO_VEHICULO',
  'AIRTABLE_VEH_VEH_ID_PERSONAL_CORE', 'AIRTABLE_VEH_VEH_PROPIETARIO_TIPO', 'AIRTABLE_VEH_VEH_PROPIETARIO_NOMBRE',
  'AIRTABLE_VEH_VEH_PROPIETARIO_DOCUMENTO', 'AIRTABLE_VEH_VEH_OBSERVACIONES', 'AIRTABLE_VEH_VEH_ACTIVO',
  'AIRTABLE_VEH_VEH_DOCUMENTOS_LINK', 'AIRTABLE_VEH_VEH_CREATED_AT', 'AIRTABLE_VEH_VEH_UPDATED_AT',
  'AIRTABLE_VEH_DOC_ID', 'AIRTABLE_VEH_DOC_VEHICULO_LINK', 'AIRTABLE_VEH_DOC_TIPO_DOCUMENTO',
  'AIRTABLE_VEH_DOC_NUMERO_DOCUMENTO', 'AIRTABLE_VEH_DOC_FECHA_EXPEDICION', 'AIRTABLE_VEH_DOC_FECHA_VENCIMIENTO',
  'AIRTABLE_VEH_DOC_URL_DOCUMENTO', 'AIRTABLE_VEH_DOC_ENTIDAD_EMISORA', 'AIRTABLE_VEH_DOC_ESTADO',
  'AIRTABLE_VEH_DOC_CREATED_AT', 'AIRTABLE_VEH_LIC_ID', 'AIRTABLE_VEH_LIC_ID_PERSONAL_CORE',
  'AIRTABLE_VEH_LIC_NUMERO_LICENCIA', 'AIRTABLE_VEH_LIC_CATEGORIA', 'AIRTABLE_VEH_LIC_FECHA_EXPEDICION',
  'AIRTABLE_VEH_LIC_FECHA_VENCIMIENTO', 'AIRTABLE_VEH_LIC_ORGANISMO_TRANSITO', 'AIRTABLE_VEH_LIC_URL_LICENCIA',
  'AIRTABLE_VEH_LIC_ESTADO', 'AIRTABLE_VEH_LIC_CREATED_AT', 'AIRTABLE_VEH_ALERT_ID',
  'AIRTABLE_VEH_ALERT_TIPO_ALERTA', 'AIRTABLE_VEH_ALERT_ENTIDAD_TIPO', 'AIRTABLE_VEH_ALERT_ENTIDAD_ID',
  'AIRTABLE_VEH_ALERT_DESTINATARIO', 'AIRTABLE_VEH_ALERT_FECHA_ENVIO', 'AIRTABLE_VEH_ALERT_ENVIADO',
  'SENDGRID_RESPONSABLE_SST_EMAIL'
]).concat([
  // Sociodemográfico
  'AIRTABLE_SOCIO_CAMPANAS_NOMBRE', 'AIRTABLE_SOCIO_CAMPANAS_PERIODO', 'AIRTABLE_SOCIO_CAMPANAS_ANO',
  'AIRTABLE_SOCIO_CAMPANAS_FECHA_INICIO', 'AIRTABLE_SOCIO_CAMPANAS_FECHA_CIERRE', 'AIRTABLE_SOCIO_CAMPANAS_ESTADO',
  'AIRTABLE_SOCIO_CAMPANAS_CREADO_POR', 'AIRTABLE_SOCIO_CAMPANAS_RESPUESTAS_LINK', 'AIRTABLE_SOCIO_CAMPANAS_TOKENS_LINK',
  'AIRTABLE_SOCIO_TOKENS_TOKEN', 'AIRTABLE_SOCIO_TOKENS_CAMPANA', 'AIRTABLE_SOCIO_TOKENS_PERSONAL',
  'AIRTABLE_SOCIO_TOKENS_USADO', 'AIRTABLE_SOCIO_TOKENS_FECHA_USO', 'AIRTABLE_SOCIO_TOKENS_RESPUESTAS_LINK',
  'AIRTABLE_SOCIO_RESP_CAMPANA', 'AIRTABLE_SOCIO_RESP_TOKEN', 'AIRTABLE_SOCIO_RESP_PERSONAL',
  'AIRTABLE_SOCIO_RESP_NOMBRE_COMPLETO', 'AIRTABLE_SOCIO_RESP_NUMERO_DOCUMENTO', 'AIRTABLE_SOCIO_RESP_FECHA_NACIMIENTO',
  'AIRTABLE_SOCIO_RESP_GENERO', 'AIRTABLE_SOCIO_RESP_ESTADO_CIVIL', 'AIRTABLE_SOCIO_RESP_MUNICIPIO',
  'AIRTABLE_SOCIO_RESP_ESCOLARIDAD', 'AIRTABLE_SOCIO_RESP_ESTUDIANDO', 'AIRTABLE_SOCIO_RESP_CARRERA_ACTUAL',
  'AIRTABLE_SOCIO_RESP_ESTRATO', 'AIRTABLE_SOCIO_RESP_TIPO_VIVIENDA', 'AIRTABLE_SOCIO_RESP_PERSONAS_CARGO',
  'AIRTABLE_SOCIO_RESP_CARGO', 'AIRTABLE_SOCIO_RESP_AREA_TRABAJO', 'AIRTABLE_SOCIO_RESP_TIPO_CONTRATO',
  'AIRTABLE_SOCIO_RESP_FECHA_INGRESO', 'AIRTABLE_SOCIO_RESP_TURNO', 'AIRTABLE_SOCIO_RESP_OTRO_EMPLEO',
  'AIRTABLE_SOCIO_RESP_DESC_OTRO_EMPLEO', 'AIRTABLE_SOCIO_RESP_TRANSPORTE', 'AIRTABLE_SOCIO_RESP_TIEMPO_DESPLAZAMIENTO',
  'AIRTABLE_SOCIO_RESP_TIEMPO_LIBRE', 'AIRTABLE_SOCIO_RESP_DESC_OTRO_TIEMPO_LIBRE', 'AIRTABLE_SOCIO_RESP_PRACTICA_DEPORTE',
  'AIRTABLE_SOCIO_RESP_CUAL_DEPORTE', 'AIRTABLE_SOCIO_RESP_FUMA', 'AIRTABLE_SOCIO_RESP_ALCOHOL',
  'AIRTABLE_SOCIO_RESP_ENFERMEDAD_CRONICA', 'AIRTABLE_SOCIO_RESP_CUAL_ENFERMEDAD', 'AIRTABLE_SOCIO_RESP_TRATAMIENTO_MEDICO',
  'AIRTABLE_SOCIO_RESP_DESC_TRATAMIENTO', 'AIRTABLE_SOCIO_RESP_DISCAPACIDAD', 'AIRTABLE_SOCIO_RESP_CUAL_DISCAPACIDAD',
  'AIRTABLE_SOCIO_RESP_ENFERMEDAD_LABORAL', 'AIRTABLE_SOCIO_RESP_DESC_ENF_LABORAL', 'AIRTABLE_SOCIO_RESP_ACCIDENTES_PREVIOS',
  'AIRTABLE_SOCIO_RESP_DESC_ACCIDENTES', 'AIRTABLE_SOCIO_RESP_ACEPTA_POLITICA', 'AIRTABLE_SOCIO_RESP_FIRMA_VERACIDAD',
  'AIRTABLE_SOCIO_RESP_FIRMA', 'AIRTABLE_SOCIO_INFORMES_CAMPANA', 'AIRTABLE_SOCIO_INFORMES_TOTAL_RESPUESTAS',
  'AIRTABLE_SOCIO_INFORMES_GENERADO_POR', 'AIRTABLE_SOCIO_INFORMES_URL_PDF'
]).concat([
  // Inducciones
  'AIRTABLE_IND_REG_ID_INDUCCION', 'AIRTABLE_IND_REG_ID_EMPLEADO_CORE', 'AIRTABLE_IND_REG_NOMBRE_EMPLEADO',
  'AIRTABLE_IND_REG_NUMERO_DOCUMENTO', 'AIRTABLE_IND_REG_CARGO', 'AIRTABLE_IND_REG_TIPO',
  'AIRTABLE_IND_REG_FECHA_REALIZACION', 'AIRTABLE_IND_REG_FECHA_VENCIMIENTO', 'AIRTABLE_IND_REG_RESPONSABLE_SST',
  'AIRTABLE_IND_REG_FIRMA_URL', 'AIRTABLE_IND_REG_ESTADO', 'AIRTABLE_IND_REG_ESTADO_EVALUACION',
  'AIRTABLE_IND_REG_EVALUACION_ID', 'AIRTABLE_IND_REG_PUNTAJE_EVALUACION', 'AIRTABLE_IND_REG_CERTIFICADO_URL',
  'AIRTABLE_IND_REG_FECHA_EXPORTACION', 'AIRTABLE_IND_REG_OBSERVACIONES', 'AIRTABLE_IND_REG_LINK_TOKENS',
  'AIRTABLE_IND_REG_LINK_ALERTAS', 'AIRTABLE_IND_TKN_TOKEN_ID', 'AIRTABLE_IND_TKN_INDUCCION_ID',
  'AIRTABLE_IND_TKN_ID_EMPLEADO_CORE', 'AIRTABLE_IND_TKN_HASH_FIRMA', 'AIRTABLE_IND_TKN_FECHA_GENERACION',
  'AIRTABLE_IND_TKN_FECHA_EXPIRACION', 'AIRTABLE_IND_TKN_ESTADO_TOKEN', 'AIRTABLE_IND_TKN_LINK_REGISTROS',
  'AIRTABLE_IND_CONST_ID_CONSTANCIA', 'AIRTABLE_IND_CONST_ID_INDUCCION', 'AIRTABLE_IND_CONST_FECHA_REALIZACION',
  'AIRTABLE_IND_CONST_HORA_INICIO', 'AIRTABLE_IND_CONST_HORA_FIN', 'AIRTABLE_IND_CONST_LUGAR_REALIZACION',
  'AIRTABLE_IND_CONST_RESPONSABLE_SST', 'AIRTABLE_IND_CONST_OBSERVACIONES', 'AIRTABLE_IND_ALR_ID_ALERTA',
  'AIRTABLE_IND_ALR_INDUCCION_ID', 'AIRTABLE_IND_ALR_ID_EMPLEADO_CORE', 'AIRTABLE_IND_ALR_NOMBRE_EMPLEADO',
  'AIRTABLE_IND_ALR_CORREO_DESTINO', 'AIRTABLE_IND_ALR_TIPO_ALERTA', 'AIRTABLE_IND_ALR_FECHA_VENCIMIENTO',
  'AIRTABLE_IND_ALR_FECHA_ALERTA', 'AIRTABLE_IND_ALR_ENVIADA', 'AIRTABLE_IND_ALR_FECHA_ENVIO',
  'AIRTABLE_IND_ALR_OBSERVACIONES_ENVIO', 'AIRTABLE_IND_ALR_LINK_REGISTROS', 'IND_VIGENCIA_MESES',
  'IND_TOKEN_EXPIRACION_HORAS', 'IND_PLANTILLA_EVALUACION_CODIGO', 'IND_RESPONSABLE_SST_NOMBRE',
  'IND_RESPONSABLE_SST_CEDULA', 'IND_CORREO_SST', 'IND_FIRMA_RESPONSABLE_SST', 'IND_S3_PREFIX_CERTIFICADOS',
  'IND_S3_PREFIX_FIRMAS', 'IND_ALERTA_DIAS_ANTICIPACION', 'FIRMA_RESPONSABLE_SST_S3_KEY', 'USE_S3_FOR_SIGNATURES'
]).concat([
  // Comités
  'MIEMBROS_COMITE_ID_FIELD', 'MIEMBROS_COMITE_EMPLEADO_CORE_FIELD', 'MIEMBROS_COMITE_NOMBRE_FIELD',
  'MIEMBROS_COMITE_CEDULA_FIELD', 'MIEMBROS_COMITE_CARGO_FIELD', 'MIEMBROS_COMITE_COMITE_FIELD',
  'MIEMBROS_COMITE_ROL_FIELD', 'MIEMBROS_COMITE_REPRESENTACION_FIELD', 'MIEMBROS_COMITE_ESTADO_FIELD',
  'MIEMBROS_COMITE_FECHA_INICIO_FIELD', 'MIEMBROS_COMITE_FECHA_FIN_FIELD', 'ASISTENCIA_COMITES_ID_FIELD',
  'ASISTENCIA_COMITES_MIEMBRO_LINK_FIELD', 'ASISTENCIA_COMITES_COMITE_FIELD', 'ASISTENCIA_COMITES_ACTA_COPASST_LINK_FIELD',
  'ASISTENCIA_COMITES_ACTA_COCOLAB_LINK_FIELD', 'ASISTENCIA_COMITES_ASISTIO_FIELD', 'ASISTENCIA_COMITES_FIRMA_FIELD',
  'ASISTENCIA_COMITES_FECHA_FIRMA_FIELD', 'ASISTENCIA_COMITES_OBSERVACIONES_FIELD', 'COMPROMISOS_ID_FIELD',
  'COMPROMISOS_COMITE_FIELD', 'COMPROMISOS_ACTA_COPASST_LINK_FIELD', 'COMPROMISOS_ACTA_COCOLAB_LINK_FIELD',
  'COMPROMISOS_DESCRIPCION_FIELD', 'COMPROMISOS_RESPONSABLE_FIELD', 'COMPROMISOS_FECHA_LIMITE_FIELD',
  'COMPROMISOS_CUMPLIDO_FIELD', 'COPASST_ACTAS_ID_FIELD', 'COPASST_ACTAS_NUMERO_ACTA_FIELD',
  'COPASST_ACTAS_FECHA_REUNION_FIELD', 'COPASST_ACTAS_HORA_INICIO_FIELD', 'COPASST_ACTAS_HORA_CIERRE_FIELD',
  'COPASST_ACTAS_LUGAR_FIELD', 'COPASST_ACTAS_MES_EVALUADO_FIELD', 'COPASST_ACTAS_NOVEDADES_FIELD',
  'COPASST_ACTAS_INCIDENTES_FIELD', 'COPASST_ACTAS_INCIDENTES_DETALLE_FIELD', 'COPASST_ACTAS_ACCIDENTES_FIELD',
  'COPASST_ACTAS_ACCIDENTES_DETALLE_FIELD', 'COPASST_ACTAS_ESTADO_FIELD', 'COPASST_ACTAS_URL_DOCUMENTO_FIELD',
  'COPASST_ACTAS_FECHA_EXPORT_FIELD', 'COPASST_ACTAS_FIRMA_PRESIDENTE_FIELD', 'COPASST_ACTAS_FIRMA_SECRETARIO_FIELD',
  'COPASST_ACTAS_CREATED_AT_FIELD', 'COPASST_ACTAS_UPDATED_AT_FIELD', 'COPASST_ACTAS_ASISTENTES_LINK_FIELD',
  'COPASST_ACTAS_COMPROMISOS_LINK_FIELD', 'COPASST_ACTAS_CONDICIONES_LINK_FIELD', 'COPASST_ACTAS_CAPACITACIONES_LINK_FIELD',
  'COPASST_CONDICIONES_ID_FIELD', 'COPASST_CONDICIONES_ACTA_LINK_FIELD', 'COPASST_CONDICIONES_DESCRIPCION_FIELD',
  'COPASST_CONDICIONES_RESULTADO_FIELD', 'COPASST_CONDICIONES_OBSERVACION_FIELD', 'COCOLAB_ACTAS_ID_FIELD',
  'COCOLAB_ACTAS_NUMERO_ACTA_FIELD', 'COCOLAB_ACTAS_FECHA_REUNION_FIELD', 'COCOLAB_ACTAS_HORA_INICIO_FIELD',
  'COCOLAB_ACTAS_HORA_CIERRE_FIELD', 'COCOLAB_ACTAS_LUGAR_FIELD', 'COCOLAB_ACTAS_MES_EVALUADO_FIELD',
  'COCOLAB_ACTAS_QUEJAS_ACOSO_FIELD', 'COCOLAB_ACTAS_QUEJAS_DETALLE_FIELD', 'COCOLAB_ACTAS_CONFLICTOS_FIELD',
  'COCOLAB_ACTAS_CONFLICTOS_DETALLE_FIELD', 'COCOLAB_ACTAS_ESTADO_FIELD', 'COCOLAB_ACTAS_URL_DOCUMENTO_FIELD',
  'COCOLAB_ACTAS_FECHA_EXPORT_FIELD', 'COCOLAB_ACTAS_FIRMA_PRESIDENTE_FIELD', 'COCOLAB_ACTAS_FIRMA_SECRETARIA_FIELD',
  'COCOLAB_ACTAS_CREATED_AT_FIELD', 'COCOLAB_ACTAS_UPDATED_AT_FIELD', 'COCOLAB_ACTAS_ASISTENTES_LINK_FIELD',
  'COCOLAB_ACTAS_COMPROMISOS_LINK_FIELD', 'COCOLAB_ACTAS_ACCIONES_LINK_FIELD', 'COCOLAB_ACCIONES_ID_FIELD',
  'COCOLAB_ACCIONES_ACTA_LINK_FIELD', 'COCOLAB_ACCIONES_DESCRIPCION_FIELD', 'COCOLAB_ACCIONES_CATEGORIA_FIELD',
  'ASISTENCIA_EXCLUIR_ID_EMPLEADOS', 'CAMPO_NO_DEFINIDO', 'AIRTABLE_INFOEXT_TABLE_ID',
  'AIRTABLE_INFOEXT_TIPO_EXTINTOR', 'AIRTABLE_INFOEXT_CAPACIDAD', 'AIRTABLE_INFOEXT_CLASE_AGENTE',
  'AIRTABLE_INFOEXT_FECHA_PROXIMA_RECARGA', 'AIRTABLE_VERKIT_TABLE_ID'
]));

console.log('\n📊 ANÁLISIS DE VARIABLES DE ENTORNO\n');
console.log(`Total de variables en .env.local: ${envVars.size}`);
console.log(`Total de variables usadas en el código: ${usedVars.size}\n`);

// Detectar variables no utilizadas
const unusedVars = [];
for (const [varName, value] of envVars) {
  if (!usedVars.has(varName) && !varName.startsWith('NEXT_PUBLIC_SIGNING')) {
    unusedVars.push(varName);
  }
}

console.log('❌ VARIABLES NO UTILIZADAS:\n');
unusedVars.forEach(varName => {
  console.log(`  - ${varName}`);
});

console.log(`\n📈 RESUMEN:`);
console.log(`  Variables a CONSERVAR: ${envVars.size - unusedVars.length}`);
console.log(`  Variables a ELIMINAR: ${unusedVars.length}`);
console.log(`  Ahorro estimado: ~${(unusedVars.length / envVars.size * 100).toFixed(1)}%`);

// Generar archivo limpio
const cleanedLines = envLines.filter(line => {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) return true;
  const match = trimmed.match(/^([A-Z_0-9]+)=/);
  if (!match) return true;
  return !unusedVars.includes(match[1]);
});

const cleanedContent = cleanedLines.join('\n');
fs.writeFileSync(path.join(__dirname, '.env.local.clean'), cleanedContent);
console.log('\n✅ Archivo limpio generado: .env.local.clean');
console.log('\n⚠️  IMPORTANTE: Revisa el archivo .env.local.clean antes de reemplazar .env.local');
